site_name: Boardroom Learn | DAO Wiki
site_description: A community resource covering all things DAOs
site_url: https://learn.boardroom.info
theme:
  name: 'material'
  custom_dir: 'docs/material'
  palette:
    primary: 'deep purple'
    accent: 'white'
  logo: 'logo.png'
  favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

extra_css: [extra.css]
markdown_extensions:
  - meta

repo_name: 'boardroom-inc/stateless'
repo_url: 'https://github.com/boardroom-inc/stateless'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/boardroom-inc/stateless'
    - type: 'twitter'
      link: 'https://twitter.com/boardroom_info'
    - type: 'medium'
      link: 'https://medium.com/stateless'
    - type: 'comment'
      link: 'https://discordapp.com/invite/gw8AM98'
    - type: 'instagram'
      link: 'https://www.instagram.com/stateless_io/'

google_analytics:
  - 'UA-125892125-2'
  - 'auto'

nav:
- Home: 'index.md'
- Dashboard: 'https://boardroom.info/'
- Screener: 'https://boardroom.info/screener'
- Newsletter: 'https://governance.substack.com'
- Publication: 'https://stateless.mirror.xyz'
- Podcast: 'https://anchor.fm/stateless'
- DAO Basics:
  - 'What is a DAO?': 'DAO-basics/what-is-a-dao.md'
  - 'Types of DAOs': 'DAO-basics/types-of-daos.md'
  - 'Why DAOs': 'DAO-basics/why-daos.md'
  - 'DAO Treasuries': 'DAO-basics/dao-treasuries.md'
  - 'Resources': 'DAO-basics/resources.md'
- Guides:
  - 'Getting Started': 'DAO-guides/getting-started.md'
  - 'Participating in a DAO': 'DAO-guides/participating-in-a-dao.md'
  - 'Starting a DAO': 'DAO-guides/starting-a-dao.md'
- Tooling:
  - 'DAO Tooling': 'DAO-tooling/tooling-overview.md'
  - Frameworks:
    - 'What is a Governance Framework?': 'DAO-frameworks/what-is-a-governance-framework?.md'
    - 'Aragon': 'DAO-frameworks/aragon.md'
    - 'Colony': 'DAO-frameworks/colony.md'
    - 'Commonwealth': 'DAO-frameworks/commonwealth.md'
    - 'Compound Governor Alpha': 'DAO-frameworks/compound-alpha.md'
    - 'Compound Governor Bravo': 'DAO-frameworks/compound-bravo.md'
    - 'DAOStack': 'DAO-frameworks/daostack.md'
    - 'Habitat': 'DAO-frameworks/habitat.md'
    - 'Moloch': 'DAO-frameworks/moloch.md'
    - 'Openlaw': 'DAO-frameworks/openlaw.md'
    - 'Snapshot': 'DAO-frameworks/snapshot.md'
  - Controllers:
    - 'What are Controllers?': 'DAO-tooling/controllers/what-are-controllers.md'
    - 'Alchemy': 'DAO-tooling/controllers/alchemy.md'
    - 'DaoHaus': 'DAO-tooling/controllers/daohaus.md'
    - 'Vocdoni': 'DAO-tooling/controllers/vocdoni.md'
  - Treasury:
    - 'What is the DAO Treasury Infrastructure?': 'DAO-tooling/treasury/treasury-infrastructure.md'
    - 'Coordinape': 'DAO-tooling/treasury/coordinape.md'
    - 'Enzyme': 'DAO-tooling/treasury/enzyme.md'
    - 'Gnosis Safe': 'DAO-tooling/treasury/gnosis-safe.md'
    - 'Llama': 'DAO-tooling/treasury/llama.md'
    - 'Paracel': 'DAO-tooling/treasury/paracel.md'
  - Work:
    - 'What is the DAO Work Infrastructure': 'DAO-tooling/work/work-infratructure-overview.md'
    - 'RabbitHole': 'DAO-tooling/work/rabbithole.md'
    - 'Radicle': 'DAO-tooling/work/radicle.md'
    - 'SourceCred': 'DAO-tooling/work/sourcecred.md'
    - 'Squad DAO': 'DAO-tooling/work/squad-dao.md'
  - Aggregators:
    - 'What are Aggregators?': 'DAO-tooling/aggregators/what-are-aggregators.md'
    - 'Boardroom': 'DAO-tooling/aggregators/boardroom.md'
    - 'Tally': 'DAO-tooling/aggregators/tally.md'
  - 'Communication': 'DAO-tooling/communication.md'
  - 'Resources': 'DAO-tooling/resources.md'
- Ecosystem:
  - 'DAO Ecosystem': 'DAO-ecosystem/dao-ecosystem.md'
  - Frameworks:
    - 'What is a Governance Framework?': 'DAO-frameworks/what-is-a-governance-framework?.md'
    - 'Aragon': 'DAO-frameworks/aragon.md'
    - 'Colony': 'DAO-frameworks/colony.md'
    - 'Commonwealth': 'DAO-frameworks/commonwealth.md'
    - 'Compound Governor Alpha': 'DAO-frameworks/compound-alpha.md'
    - 'Compound Governor Bravo': 'DAO-frameworks/compound-bravo.md'
    - 'DAOStack': 'DAO-frameworks/daostack.md'
    - 'Habitat': 'DAO-frameworks/habitat.md'
    - 'Moloch': 'DAO-frameworks/moloch.md'
    - 'Openlaw': 'DAO-frameworks/openlaw.md'
    - 'Snapshot': 'DAO-frameworks/snapshot.md'
  - Investment DAOs:
    - 'What are Investment DAOs?': 'DAO-ecosystem/investment-daos/what-are-investment-daos.md'
    - 'BitDAO': 'DAO-ecosystem/investment-daos/bitdao.md'
    - 'Duck DAO': 'DAO-ecosystem/investment-daos/duckdao.md'
    - 'Flamingo': 'DAO-ecosystem/investment-daos/flamingo.md'
    - 'Free Company': 'DAO-ecosystem/investment-daos/free-company.md'
    - 'Komorebi': 'DAO-ecosystem/investment-daos/komorebi.md'
    - 'MetaCartel': 'DAO-ecosystem/investment-daos/metacartel.md'
    - 'theLAO': 'DAO-ecosystem/investment-daos/the-lao.md'
    - 'UdacityFund': 'DAO-ecosystem/investment-daos/udacityfund.md'
  - Grant DAOs:
    - 'What are Grant DAOs?': 'DAO-ecosystem/grant-daos/what-are-grant-daos.md'
    - 'Aave Grants': 'DAO-ecosystem/grant-daos/aave-grants.md'
    - 'Audius Grants': 'DAO-ecosystem/grant-daos/audius-grants.md'
    - 'Compound Grants': 'DAO-ecosystem/grant-daos/compound-grants.md'
    - 'MetaCartel Ventures': 'DAO-ecosystem/grant-daos/metacartel-ventures.md'
    - 'Mint Fund': 'DAO-ecosystem/grant-daos/mint-fund.md'
    - 'Moloch DAO': 'DAO-ecosystem/grant-daos/moloch-dao.md'
    - 'Sevens Foundation': 'DAO-ecosystem/grant-daos/sevens-foundation.md'
    - 'Uniswap Grants': 'DAO-ecosystem/grant-daos/uniswap-grants.md'
  - Collector DAOs:
    - 'What are Collector DAOs?': 'DAO-ecosystem/collector-daos/what-are-collector-daos.md'
    - 'BeetsDAO': 'DAO-ecosystem/collector-daos/beetsdao.md'
    - 'BRRDAO': 'DAO-ecosystem/collector-daos/brrdao.md'
    - 'FingerprintsDAO': 'DAO-ecosystem/collector-daos/fingerprintsdao.md'
    - 'Flamingo': 'DAO-ecosystem/collector-daos/flamingo.md'
    - 'Gremlins': 'DAO-ecosystem/collector-daos/gremlins.md'
    - 'herstoryDAO': 'DAO-ecosystem/collector-daos/herstorydao.md'
    - 'JennyDAO': 'DAO-ecosystem/collector-daos/jennydao.md'
    - 'MeebitsDAO': 'DAO-ecosystem/collector-daos/meebitsdao.md'
    - 'MUSE0': 'DAO-ecosystem/collector-daos/muse0.md'
    - 'PleasrDAO': 'DAO-ecosystem/collector-daos/pleasrdao.md'
    - 'SquiggleDAO': 'DAO-ecosystem/collector-daos/squiggledao.md'
    - 'Whale': 'DAO-ecosystem/collector-daos/whale.md'
  - Protocol DAOs:
    - 'What is a Protocol DAO?': 'DAO-ecosystem/protocol-daos/what-is-a-protocol-dao.md'
    - 'Aave': 'DAO-ecosystem/protocol-daos/aave.md'
    - 'Aavegotchi': 'DAO-ecosystem/protocol-daos/aavegotchi.md'
    - 'Audius': 'DAO-ecosystem/protocol-daos/audius.md'
    - 'Badger': 'DAO-ecosystem/protocol-daos/badger.md'
    - 'Balancer': 'DAO-ecosystem/protocol-daos/balancer.md'
    - 'Compound': 'DAO-ecosystem/protocol-daos/compound.md'
    - 'Cream Finance': 'DAO-ecosystem/protocol-daos/cream-finance.md'
    - 'Curve': 'DAO-ecosystem/protocol-daos/curve.md'
    - 'Gitcoin': 'DAO-ecosystem/protocol-daos/gitcoin.md'
    - 'hDAO': 'DAO-ecosystem/protocol-daos/hdao.md'
    - 'Index Coop': 'DAO-ecosystem/protocol-daos/index-coop.md'
    - 'InstaDapp': 'DAO-ecosystem/protocol-daos/instadapp.md'
    - 'Inverse Finance': 'DAO-ecosystem/protocol-daos/inverse-finance.md'
    - 'KeeperDAO': 'DAO-ecosystem/protocol-daos/keeperdao.md'
    - 'LIDO': 'DAO-ecosystem/protocol-daos/lido.md'
    - 'Maker': 'DAO-ecosystem/protocol-daos/maker.md'
    - 'OceanDAO': 'DAO-ecosystem/protocol-daos/oceandao.md'
    - 'Olympus': 'DAO-ecosystem/protocol-daos/olympus.md'
    - 'PieDAO': 'DAO-ecosystem/protocol-daos/piedao.md'
    - 'Pool': 'DAO-ecosystem/protocol-daos/pool.md'
    - 'Rari Capital': 'DAO-ecosystem/protocol-daos/rari-capital.md'
    - 'RaribleDAO': 'DAO-ecosystem/protocol-daos/raribledao.md'
    - 'Sushi': 'DAO-ecosystem/protocol-daos/sushi.md'
    - 'Synthetix': 'DAO-ecosystem/protocol-daos/synthetix.md'
    - 'Tornado': 'DAO-ecosystem/protocol-daos/tornado.md'
    - 'Uniswap': 'DAO-ecosystem/protocol-daos/uniswap.md'
    - 'Universe': 'DAO-ecosystem/protocol-daos/universe.md'
    - 'Yearn': 'DAO-ecosystem/protocol-daos/yearn.md'
  - Service DAOs:
    - 'What is a Service DAO?': 'DAO-ecosystem/service-daos/what-is-a-service-dao.md'
    - 'AladdinDAO': 'DAO-ecosystem/service-daos/aladdindao.md'
    - 'DaoHaus': 'DAO-ecosystem/service-daos/daohaus.md'
    - 'Deep Work': 'DAO-ecosystem/service-daos/deep-work.md'
    - 'DeepDAO': 'DAO-ecosystem/service-daos/deepdao.md'
    - 'DoinGud': 'DAO-ecosystem/service-daos/doingud.md'
    - 'dOrg': 'DAO-ecosystem/service-daos/dorg.md'
    - 'DXdao': 'DAO-ecosystem/service-daos/dxdao.md'
    - 'Fire Eyes': 'DAO-ecosystem/service-daos/fire-eyes.md'
    - 'HoneyDAO': 'DAO-ecosystem/service-daos/honeydao.md'
    - 'LexDAO': 'DAO-ecosystem/service-daos/lexdao.md'
    - 'Llama': 'DAO-ecosystem/service-daos/llama.md'
    - 'MetaFactory': 'DAO-ecosystem/service-daos/metafactory.md'
    - 'MetaverseDAO': 'DAO-ecosystem/service-daos/metaversedao.md'
    - 'Myco': 'DAO-ecosystem/service-daos/myco.md'
    - 'NeptuneDAO': 'DAO-ecosystem/service-daos/neptunedao.md'
    - 'OPOLIS': 'DAO-ecosystem/service-daos/opolis.md'
    - 'PartyDAO': 'DAO-ecosystem/service-daos/partydao.md'
    - 'RAID GUILD': 'DAO-ecosystem/service-daos/raid-guild.md'
    - 'Reverie': 'DAO-ecosystem/service-daos/reverie.md'
    - 'ShinyDAO': 'DAO-ecosystem/service-daos/shinydao.md'
    - 'UniWhales': 'DAO-ecosystem/service-daos/uniwhales.md'
    - 'VitaDAO': 'DAO-ecosystem/service-daos/vitadao.md'
    - 'Yam DAO': 'DAO-ecosystem/service-daos/yam-dao.md'
    - 'YGG': 'DAO-ecosystem/service-daos/ygg.md'
  - Social DAOs:
    - 'What is a Social DAO?': 'DAO-ecosystem/social-daos/what-is-a-social-dao.md'
    - 'BAYC': 'DAO-ecosystem/social-daos/bayc.md'
    - 'Bright Moments': 'DAO-ecosystem/social-daos/bright-moments.md'
    - 'CabinDAO': 'DAO-ecosystem/social-daos/cabindao.md'
    - 'FiatLuxDAO': 'DAO-ecosystem/social-daos/fiatluxdao.md'
    - 'FWB': 'DAO-ecosystem/social-daos/fwb.md'
    - 'KrausHaus': 'DAO-ecosystem/social-daos/kraushaus.md'
    - 'Meta Gamma Delta': 'DAO-ecosystem/social-daos/meta-gamma-delta.md'
    - 'Metafam': 'DAO-ecosystem/social-daos/metafam.md'
    - 'PROOF OF HUMANITY': 'DAO-ecosystem/social-daos/proof-of-humanity.md'
    - 'ProsperDAO': 'DAO-ecosystem/social-daos/prosperdao.md'
    - 'Radicle': 'DAO-ecosystem/social-daos/radicle.md'
    - 'Seed ÃŸClub': 'DAO-ecosystem/social-daos/seed-club.md'
    - 'SongCamp': 'DAO-ecosystem/social-daos/songcamp.md'
    - 'TheWIPmeetup': 'DAO-ecosystem/social-daos/thewipmeetup.md'
  - Media DAOs:
    - 'What is a Media DAO?': 'DAO-ecosystem/media-daos/what-is-a-media-dao.md'
    - 'BanklessDAO': 'DAO-ecosystem/media-daos/banklessdao.md'
    - 'DarkstarDAO': 'DAO-ecosystem/media-daos/darkstardao.md'
    - 'FOREFRONT': 'DAO-ecosystem/media-daos/forefront.md'
    - 'GRC': 'DAO-ecosystem/media-daos/grc.md'
    - 'rekt': 'DAO-ecosystem/media-daos/rekt.md'
  - 'Resources': 'DAO-ecosystem/resources.md'
# - Governance:
#   - 'What Does Governance Mean': 'Governance/what-does-governance-mean?.md'
#   - 'On-Chain Governance': 'Governance/on-chain-governance.md'
#   - 'Off-Chain Governance': 'Governance/off-chain-governance.md'
#   - 'Soft Governance': 'Governance/soft-governance.md'
#   - 'Delegation': 'Governance/delegation.md'
#   - Governance Strategies:
#     - 'What are Governance Strategies?': 'Governance/governance-strategies/governance-strategies.md'
#     - 'Progressive Decentralization': 'Governance/governance-strategies/progressive-decentralization.md'
#   - 'Resources': 'Governance/resources.md'
- DAO Directory:
  - 'All DAOs': 'Directory/all-daos.md'
  - 'Investment DAOs': 'Directory/investment-daos.md'
  - 'Grant DAOs': 'Directory/grant-daos.md'
  - 'Collector DAOs': 'Directory/collector-daos.md'
  - 'Protocol DAOs': 'Directory/protocol-daos.md'
  - 'Service DAOs': 'Directory/service-daos.md'
  - 'Social DAOs': 'Directory/social-daos.md'
  - 'Media DAOs': 'Directory/media-daos.md'
  - 'Frameworks': 'Directory/frameworks.md'
- Glossary:
  - 'Acronyms': 'glossary/crypto-acronyms.md'
